from json_cpp import *
from time import sleep
from src import MessageClient, Message
from cellworld import Coordinates, Coordinates_list

client = MessageClient()
client.connect("127.0.0.1", 6500)
sleep(2)
print("method7")
print(client.send_request("method7", c=Coordinates(10,10)))
sleep(2)
cl = Coordinates_list()
cl.append(Coordinates(1,1))
cl.append(Coordinates(2,2))
cl.append(Coordinates(3,3))
print("method8")
print(client.send_request("method8", cl=cl))

sleep(2)
print("method1")
print(client.send_request("method1", v=10))
sleep(2)
print("method2")
print(client.send_request("method2", v=30))
sleep(2)
print("method3")
print(client.send_request("method3", v1=130, v2=230))
sleep(2)
print("method4")
print(client.send_message("method4", v=1))
print(client.send_message("method4", v=1))
print(client.send_message("method4", v=2))
print(client.send_message("method4", v=3))
print(client.send_message("method4", v=5))
print(client.send_message("method4", v=8))
print(client.send_message("method4", v=13))
print(client.send_message("method4", v=21))
sleep(2)
print("method6")
print(client.send_request("method6"))
sleep(2)
print("method5")
print(client.send_request("method5", i=130, f=1.4, s="test"))
sleep(2)
print("stopping")
print(client.send_message(Message("stop")))
sleep(3)
